from typing import Any, Union, Tuple
from icalendar.prop import vText, vInt, vCategory, vDDDTypes

class Todo():

    singletons : Tuple[str]

    def __setitem__(self, key : str, value : object) -> None: ...
    def __getitem__(self, key : str) -> Union[vText, vInt, vCategory, vDDDTypes]: ...
    def __delitem__(self, key : str) -> None: ...
    def __contains__(self, key : str) -> bool: ...
    def add(self, name : str, value : Any, parameters=None, encode=1) -> None: ...

