# SPDX-FileCopyrightText: 2022 Martin Byrenheid <martin@byrenheid.net>
#
# SPDX-License-Identifier: GPL-3.0-or-later

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
