CATEGORY_INCLUDE_PREFIX = "+"
CATEGORY_EXCLUDE_PREFIX = "-"

DEFAULT_DATE_FORMAT = "%Y-%m-%d"
DEFAULT_DATETIME_FORMAT = "%Y-%m-%dT%H:%M"
RELATIVE_DATE_TIME_SEPARATOR = "@"
RELATIVE_DATE_TIME_FORMAT = "%H:%M"
